# Generated by Django 4.2.13 on 2024-05-22 09:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Content",
            new_name="MessageContent",
        ),
        migrations.RenameModel(
            old_name="Message",
            new_name="MessageInfo",
        ),
    ]
